[project]
name = "tensor-utils"        # project name
version = "0.1.4"
description = """
Project utilities for tensor repo. Now includes:\n
 + Tucker decomposition and sparse tensor operations.
 + Similarity calculations
 + Config and routing
 + dependencies
"""
requires-python = ">=3.9"
dependencies = [
    "cupy==13.6.0",
    "matplotlib==3.10.8",
    "numpy==2.3.5",
    "nvidia-ml-py==13.580.82",
    "pyTensorlab==2025.12.0",
    "requests==2.32.5",
    "seaborn==0.13.2",
    "sparse==0.17.0",
    "tensorflow==2.20.0",
    "tensorly==0.9.0",
    "threadpoolctl==3.6.0",
    "torch==2.9.0",
    "tqdm==4.67.1",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# We only expose standalone modules here, NOT packages,
# to avoid accidentally packaging `semsimlib_local` etc.
py-modules = ["utils", "tucker_tensor", "sparse_ops", "similarity", "distance", "config", "routing"]
packages = []
