python3 -m tensormet.scripts.nnt \
           --dataset frame_based \
           --method siiSoftPlus \
           --divergence kl \
           --dim 4000 \
           --order 5 \
           --rank 50,50,50,50,50 \
           --name testMultiDim \
           --shared-factors "1-2,2-3,3-4" \
           --verbose t \
           --max-cpu-frac 0.8 \
           --patience 400 \
           --iterations 400  \
           --rec-log-every 2 \
           --largedim true \
           --sem-check-every 10 \
           --random-state 1 \
           --normalize-factors true \
           --return-errors full \
           --overwrite true \
           --sem-fitness-target 10000