python3 -m tensormet.scripts.nnt \
           --dataset fineweb-en \
           --method siiSoftPlus \
           --divergence kl \
           --dim 6000 \
           --order 3 \
           --rank 100 \
           --name testMultiDim \
           --shared-factors "1-2" \
           --verbose t \
           --max-cpu-frac 0.25 \
           --patience 100 \
           --iterations 100  \
           --rec-log-every 1 \
           --largedim true \
           --sem-check-every 2 \
           --random-state 1 \
           --normalize-factors true \
           --return-errors full \
           --overwrite true \
           --sem-error-type "all"